require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path

target 'Slurp' do
  config = use_native_modules!

   # Add the project and build configurations
    project 'Slurp',
      'Dev.Debug' => :debug, # '{Build Configuration name}' => :{debug or release}
      'Debug' => :debug,
      'Dev.Release' => :release,
      'Release' => :release

  use_flipper!({'Flipper' => '0.126.0', configurations: ['Debug', 'Dev.Debug']}) # Add the Build Configuration name (not scheme name)


  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'SlurpTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#    use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.126.0', 'Flipper-RSocket' => '1.3.1' })

   post_install do |installer|
     react_native_post_install(installer)
     __apply_Xcode_12_5_M1_post_install_workaround(installer)
   end
end

